### ISSUE TITLE
Using MetaICL for Unconstrained Generation

### ISSUE THREAD

**Issue by aaronmueller** [facebookresearch/MetaICL#12]
Currently, the "options" field is required in any test set .json(l) for the data to load without throwing exceptions: https://github.com/facebookresearch/MetaICL/blob/ec0f1c199965f54d4b4d35556e5ca9ba0a6719ab/metaicl/data.py#L189

While the original use-case is to evaluate on multiple-choice or classification problems only, I'd also be interested in evaluating the non-QA models on datasets like SQuAD or NaturalQuestions, which are not multiple-choice. It would also be interesting to observe what the model generates for conditional generation tasks in general.

I'd be willing to implement this in a PR if you think this feature would be useful!

**Comment by shmsw25** [comment]
Thank you for the suggestion and for the offer! It would definitely great to have a free-form generation added as a feature. One concern though is that the MetaICL model does not work particularly well on generation tasks like SQuAD, likely because the GPT-2 model in general works less competitively to those generation tasks (probably due to its small size). But it'd be great to revisit this again and evaluate the model on more tasks.

**Comment by thesofakillers** [comment]
In table 14, in the appendix, I see several unconstrained generation tasks (e.g. xsum, squad) used for Meta-training. These don't reappear for evaluation as you've said the model does not work particularly well on these tasks.

If the model does not work particularly well on these tasks, why train on them? Might've been interesting to explore a "Non-Generative Meta-train" setting ablation study, similarly to how "Non-QA" was considered for example.

thanks!

**Comment by shmsw25** [comment]
I agree that it makes sense to do ablation that includes datasets with options only (classification and multi-choice) -- thank you for the suggestion! I also agree that summarization tasks might be too different from all the others and it makes sense to remove them. For QA tasks like SQuAD, I think it will still benefit meta-training because it is still similar to evaluation tasks (like QA in a multi-choice setup). Note that meta-training doesn't explicitly use options but just use the ground-truth answer, so how meta-training uses the answer will have no difference between free-form/extractive QA vs. multi-choice QA).
